from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Question',
    'Choice',
    'Answer',
    'Profile',
    'Result',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Question': {
        'choices': 'Choice',
        'answers': 'Answer',
    },
    'Choice': {
        'question': 'Question',
        'pickedAnswers': 'Answer',
    },
    'Answer': {
        'question': 'Question',
        'choice': 'Choice',
        'profile': 'Profile',
    },
    'Profile': {
        'answers': 'Answer',
        'results': 'Result',
    },
    'Result': {
        'profile': 'Profile',
    },
}

# fmt: on